GET http://localhost:3001/api/users

###

GET http://localhost:3001/api/courses

###

GET http://localhost:3001/api/addresses

###

POST http://localhost:3001/api/users/2004/registration
Content-Type: application/json

{
    "course_id": "CSCI-2009"
}

###

POST http://localhost:3001/api/join
Content-Type: application/json

{
    "email": "student@example.com",
    "password": "securePassword123",
    "firstName": "John",
    "lastName": "Doe",
    "telephone": "123-456-7890",
    "street": "123 Campus Drive",
    "city": "College Town",
    "state": "UT",
    "zip_code": "84123",
    "country": "USA"
}

